### PR TITLE
[ready-to-merge] Fix dependency issues

### LINKED ISSUE #68: Re-enable tests in pallet-manta-pay
An ``inner attribute`` - ``#![cfg(feature = "runtime-benchmarks")]`` was introduced in ``lib.rs`` with this commit ec887c1 which disabled all our tests.

### LINKED ISSUE #84: Dependency Issues in Manta/Pallet-Manta-Pay/Manta-API/Manta-Types.

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes #68 
closes Manta-Network/Manta#84

* An ``inner attribute`` - ``#![cfg(feature = "runtime-benchmarks")]`` was introduced in ``lib.rs`` with this commit https://github.com/Manta-Network/pallet-manta-pay/pull/61/commits/ec887c19ff36397a5f0911e69296b6ac72b4fcf5 which disabled all our tests.
* This was also causing errors when integrating manta-pay into the manta runtime node :
   `` error: duplicate lang item in crate `std` (which `pallet_manta_pay` depends on): `panic_impl` ``
* Made it an ``outer attribute`` for the ``mod runtime_benchmark;`` line.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -102,7 +102,9 @@
 // Ensure we're `no_std` when compiling for Wasm.
 // #![cfg_attr(not(feature = "std"), no_std)]
 #![no_std]
-#![cfg(feature = "runtime-benchmarks")]
+
+#[cfg(test)]
+//#![cfg(feature = "runtime-benchmarks")]
```
Comment (ghzlatarev) [inline src/lib.rs:107]: Can someone explain what this was supposed to do.

File: src/lib.rs [hunk 2]
```diff
@@ -102,7 +102,8 @@
 // Ensure we're `no_std` when compiling for Wasm.
 // #![cfg_attr(not(feature = "std"), no_std)]
 #![no_std]
-#![cfg(feature = "runtime-benchmarks")]
+//#![cfg(feature = "runtime-benchmarks")]
```
Comment (ghzlatarev) [inline src/lib.rs]: Adding this ``#![cfg(feature = "runtime-benchmarks")]`` disables all our tests. Without it we fail the integration check in manta-node.
Anyone got an idea what is going on exactly ?

File: Cargo.toml [hunk 3]
```diff
@@ -25,14 +25,21 @@ data-encoding = { version = "2.3.2", default-features = false, features = [ "all
 log = { version = "0.4.14", default-features = false }
 
 # Arkworks dependencies
+
+# Attention! This needs to be included before the manta dependencies.
 ark-std = { version = "0.2.0", default-features = false }
```
Comment (ghzlatarev) [inline Cargo.toml:30]: Oh this was odd.
When I moved this with the other arkworks dependencies I got an error in ``lib.rs`` :
```
use ark_std::vec::Vec;
    |     ^^^^^^^ use of undeclared crate or module `ark_std`
```
Guessing it has to be included before our manta dependencies for some reason.

Will update the comment when i figure out exactly why.

File: src/lib.rs (hunk 2 above)
Comment (ghzlatarev) [reply src/lib.rs]: Learned the difference between inner and outer attribute.

**Review by stechu — APPROVED** [review]
Looks good. Thanks for the fix!
