### PR TITLE
[Pallet-Manta-Pay] Must fail tests for the mint_private_asset and transfer_asset extrinsics

### LINKED ISSUE #48: Manta pay extrinsics must-fail unit tests
1. mint_private_asset
    -mint_without_init_should_not_work
    -mint_zero_amount_should_not_work
    -mint_with_insufficient_origin_balance_should_not_work
    -mint_fail_on_hash_param_commit_param_mismatch
    -mint_with_invalid_commitment_should_not_work
    -mint_with_missing_commitment_should_not_work
2. transfer_asset
    -transfer_without_init_should_not_work
3. reclaim
4. private_transfer
     - transferring_with_hash_param_mismatch_should_not_work
     - transferring_spent_coin_should_not_work
     - transferring_with_invalid_ledger_state_should_not_work
     - transferring_existing_coins_should_not_work
     - transferring_with_invalid_zkp_param_should_not_work
     - transferring_with_zkp_verification_fail_should_not_work

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes #48 

* Adding the following must-fail tests for the mint_private_asset extrinsic
    - mint_without_init_should_not_work
    - mint_zero_amount_should_not_work
    - mint_with_insufficient_origin_balance_should_not_work
    - mint_with_eisting_coin_should_not_work
    - mint_with_hash_param_mismatch_should_not_work
    - mint_with_commit_param_mismatch_should_not_work
    - mint_with_invalid_commitment_should_not_work

* Adding the following must-fail tests for the transfer_asset extrinsic
    - transferring_without_init_should_not_work
  
* Fixed usage of wrong weight function for the ```init_asset``` extrinsic

### CODE REVIEW

File: src/test/frame.rs [hunk 1]
```diff
@@ -126,8 +126,56 @@ fn test_mint_should_work() {
 		assert_eq!(PoolBalance::get(TEST_ASSET), 10);
 		let coin_shards = CoinShards::get();
 		assert!(coin_shards.exist(&asset.commitment));
-		let sn_list = VNList::get();
-		assert_eq!(sn_list.len(), 0);
+		let vn_list = VNList::get();
```
Comment (ghzlatarev) [inline src/test/frame.rs:129]: VNList is for Void Number, please correct me if I'm misunderstanding something.

Comment (zhenfeizhang) [reply src/test/frame.rs:129]: Yes it is void number

**Comment by ghzlatarev** [comment]
The last commit is not intended... gong to revert it.

File: src/test/frame.rs [hunk 2]
```diff
@@ -126,8 +126,72 @@ fn test_mint_should_work() {
...
+
+		assert_noop!(
+			Assets::mint_private_asset(Origin::signed(1), payload),
+			Error::<Test>::BalanceLow
+		);
+	});
+}
+
+#[test]
+fn mint_with_eisting_coin_should_not_work() {
```
Comment (ghzlatarev) [inline src/test/frame.rs]: Spelling mistake - fix.

**Review by zhenfeizhang — APPROVED** [review]
LGTM
