### PR TITLE
Must fail tests for the private_transfer extrinsic

### LINKED ISSUE #48: Manta pay extrinsics must-fail unit tests
1. mint_private_asset
    -mint_without_init_should_not_work
    -mint_zero_amount_should_not_work
    -mint_with_insufficient_origin_balance_should_not_work
    -mint_fail_on_hash_param_commit_param_mismatch
    -mint_with_invalid_commitment_should_not_work
    -mint_with_missing_commitment_should_not_work
2. transfer_asset
    -transfer_without_init_should_not_work
3. reclaim
4. private_transfer
     - transferring_with_hash_param_mismatch_should_not_work
     - transferring_spent_coin_should_not_work
     - transferring_with_invalid_ledger_state_should_not_work
     - transferring_existing_coins_should_not_work
     - transferring_with_invalid_zkp_param_should_not_work
     - transferring_with_zkp_verification_fail_should_not_work

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes #48

* Adding the following must-fail tests for the private_transfer extrinsic
    - transferring_with_hash_param_mismatch_should_not_work
    - transferring_spent_coin_should_not_work_sender_1
    - transferring_spent_coin_should_not_work_sender_2
    - transferring_with_invalid_ledger_state_should_not_work
    - transferring_existing_coins_should_not_work
    - transferring_with_invalid_zkp_param_should_not_work
    - transferring_with_zkp_verification_fail_should_not_work
 * Adding the following must-fail tests for the reclaim extrinsic:
    - reclaim_without_init_should_not_work
    - reclaim_with_overdrawn_pool_should_not_work

### CODE REVIEW

File: src/test/frame.rs [hunk 1]
```diff
@@ -227,6 +227,119 @@ fn transferring_more_units_than_total_supply_should_not_work() {
...
+				hash_param.clone(),
+				&pk,
+				sender_1,
+				sender_2,
+				receiver_1,
+				receiver_2,
+				&mut rng,
+			);
+
+			assert_ok!(Assets::private_transfer(Origin::signed(1), payload));
```
Comment (ghzlatarev) [inline src/test/frame.rs]: @zhenfeizhang yo this test basically tries to transfer the same payload twice so it triggers ```MantaCoinSpent``` error for sender_1.
I'm not really sure how to set it up for failure on sender_2 . Any tips?

File: src/test/frame.rs [hunk 2]
```diff
@@ -354,6 +370,103 @@ fn transferring_without_init_should_not_work() {
...
+		Origin::signed(1),
+		TEST_ASSET,
+		10_000_000
+	));
+	assert_eq!(Assets::balance(1, TEST_ASSET), 10_000_000);
+	assert_eq!(PoolBalance::get(TEST_ASSET), 0);
+}
+
+#[test]
+fn transferring_spent_coin_should_not_work() {
```
Comment (ghzlatarev) [inline src/test/frame.rs]: Hmm, I'm also a little worried adding more tests like these will take too long.
Need to figure some way to reuse the state.

Comment (zhenfeizhang) [reply src/test/frame.rs]: you can add an `#[ignore]` gate for long tests -- which will be ignored unless specified
see
https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested

Comment (zhenfeizhang) [reply src/test/frame.rs]: You can also reduce the number of iterations...

File: src/test/frame.rs (hunk 1 above)
Comment (zhenfeizhang) [reply src/test/frame.rs]: if same payload is send twice, then both first and second sender tokens are duplicated.
If you want to test specifically the second sender token, you need a fresh 1st sender token. 
Does it make sense?

Comment (ghzlatarev) [reply src/test/frame.rs]: Yeah that makes sense. I'm just not sure how to set them separately yet, that's why I used the same payload as a workaround, but as you pointed it out it's not complete.
Will just figure it out.

File: src/test/frame.rs (hunk 2 above)
Comment (ghzlatarev) [reply src/test/frame.rs]: The iterations are already at 1.
Will start putting ```[ignore]```s once the CI run becomes too long.

File: src/test/frame.rs [hunk 3]
```diff
@@ -354,6 +370,186 @@ fn transferring_without_init_should_not_work() {
...
+}
+
+fn setup_for_private_transfer() {
+	assert_ok!(Assets::init_asset(
+		Origin::signed(1),
+		TEST_ASSET,
+		10_000_000
+	));
+	assert_eq!(Assets::balance(1, TEST_ASSET), 10_000_000);
+	assert_eq!(PoolBalance::get(TEST_ASSET), 0);
```
Comment (ghzlatarev) [inline src/test/frame.rs]: This can be reused better if the amount is passed as an argument.

File: src/test/frame.rs [hunk 4]
```diff
@@ -354,6 +370,258 @@ fn transferring_without_init_should_not_work() {
...
 
+fn load_zkp_keys(file_name: &str) -> Groth16Pk {
+	let mut file = File::open(file_name).unwrap();
+	let mut transfer_key_bytes: Vec<u8> = vec![];
+	file.read_to_end(&mut transfer_key_bytes).unwrap();
+	let buf: &[u8] = transfer_key_bytes.as_ref();
+	Groth16Pk::deserialize_unchecked(buf).unwrap()
+}
+
+fn setup_for_private_transfer() {
```
Comment (ghzlatarev) [inline src/test/frame.rs]: Rename this.

File: src/test/frame.rs [hunk 5]
```diff
@@ -419,30 +687,14 @@ fn mint_tokens_setup_helper() {
...
-	// load the ZKP keys
-	let mut file = File::open("transfer_pk.bin").unwrap();
-	let mut transfer_key_bytes: Vec<u8> = vec![];
-	file.read_to_end(&mut transfer_key_bytes).unwrap();
-	let buf: &[u8] = transfer_key_bytes.as_ref();
-	let pk = Groth16Pk::deserialize_unchecked(buf).unwrap();
-	let vk = pk.vk.clone();
-	let mut vk_bytes = Vec::new();
-	vk.serialize_uncompressed(&mut vk_bytes).unwrap();
-	let vk = TRANSFER_PK;
```
Comment (ghzlatarev) [inline src/test/frame.rs:443]: These lines didn't seem to do anything.
```let vk = TRANSFER_PK``` overwrites everything.

@stechu @zhenfeizhang

File: src/zkp/verifier.rs [hunk 6]
```diff
@@ -23,15 +23,56 @@ impl MantaZKPVerifier for PrivateTransferData {
...
-		let k_old_1 = CommitmentOutput::deserialize(self.sender_1.k.as_ref()).unwrap();
-		let k_old_2 = CommitmentOutput::deserialize(self.sender_2.k.as_ref()).unwrap();
-		let cm_new_1 = CommitmentOutput::deserialize(self.receiver_1.cm.as_ref()).unwrap();
-		let cm_new_2 = CommitmentOutput::deserialize(self.receiver_2.cm.as_ref()).unwrap();
-		let merkle_root_1 = HashOutput::deserialize(self.sender_1.root.as_ref()).unwrap();
-		let merkle_root_2 = HashOutput::deserialize(self.sender_2.root.as_ref()).unwrap();
+		let proof = match Groth16Proof::deserialize(self.proof.as_ref()) {
+			Ok(p) => p,
+			Err(_e) => {
+				return false;
```
Comment (ghzlatarev) [inline src/zkp/verifier.rs:37]: Currently only this exit is tested.
Either log a task or implement them in this PR.
EDIT: Logged.

File: src/test/frame.rs [hunk 7]
```diff
@@ -354,11 +361,335 @@ fn transferring_without_init_should_not_work() {
...
+				sender_2,
+				receiver_1.clone(),
+				receiver_2.clone(),
+				&mut rng,
+			);
+
+			let mut data = PrivateTransferData::deserialize(payload.as_ref());
+			data.proof = [0u8; 192];
+			let mut payload_with_bad_proof = [0u8; PRIVATE_TRANSFER_PAYLOAD_SIZE];
+			data.serialize(payload_with_bad_proof.as_mut());
```
Comment (ghzlatarev) [inline src/test/frame.rs:638]: Making a valid payload then modifying the proof then re-creating the payload is redundant work.
But otherwise I'd have to unroll ```generate_private_transfer_payload``` and that will create duplication.

File: src/lib.rs [hunk 8]
```diff
@@ -362,17 +362,17 @@ decl_module! {
...
-				!sn_list.contains(&data.sender_1.void_number),
+				!vn_list.contains(&data.sender_1.void_number),
 				<Error<T>>::MantaCoinSpent
 			);
-			sn_list.push(data.sender_1.void_number);
+			vn_list.push(data.sender_1.void_number);
 			ensure!(
-				!sn_list.contains(&data.sender_2.void_number),
+				!vn_list.contains(&data.sender_2.void_number),
 				<Error<T>>::MantaCoinSpent
```
Comment (ghzlatarev) [inline src/lib.rs:373]: These should ideally be different errors?
Might deserve to be logged for lager.
EDIT: Logged.

**Comment by ghzlatarev** [comment]
@zhenfeizhang ran the test we talked about overnight 300 times.
Looks good.

File: src/test/frame.rs (hunk 5 above)
Comment (zhenfeizhang) [reply src/test/frame.rs:443]: Yeah... The point here is to extract `vk_bytes` in line 442, and compare it with `TRANSFER_PK`

File: src/test/frame.rs (hunk 7 above)
Comment (zhenfeizhang) [reply src/test/frame.rs:638]: For testing, I think we can have some slack here.

File: src/test/frame.rs [hunk 9]
```diff
@@ -106,12 +107,54 @@ fn test_constants_should_work() {
...
+		assert_eq!(Assets::balance(2, TEST_ASSET), 19);
+		assert_eq!(Assets::balance(3, TEST_ASSET), 31);
+		assert_eq!(Assets::total_supply(TEST_ASSET), 100);
+	});
+}
+
+#[test]
+fn destroying_asset_balance_with_positive_balance_should_work() {
+	new_test_ext().execute_with(|| {
+		initialize_test(100);
```
Comment (zhenfeizhang) [inline src/test/frame.rs]: I don't think we have implemented `destroy` logic.
This should be a `must-fail` and `not_implemented!()`

**Comment by ghzlatarev** [comment]
Should be more readable now after the last few commits.

File: src/test/frame.rs (hunk 5 above)
Comment (ghzlatarev) [reply src/test/frame.rs:443]: Ahaa seems like that comparison was missing.
Will revert and add an assert.

Comment (zhenfeizhang) [reply src/test/frame.rs:443]: it is in line 445 and then get renamed in line 697

**Review by zhenfeizhang — APPROVED** [review]

File: src/test/frame.rs (hunk 5 above)
Comment (ghzlatarev) [reply src/test/frame.rs:443]: I'm a little confused. Was the original intent:
```
        let vk = pk.vk.clone();
	let mut vk_bytes = Vec::new();
	vk.serialize_uncompressed(&mut vk_bytes).unwrap();
        assert_eq!(TRANSFER_PK.get_checksum(), vk.get_checksum()); // Instead of vk = TRANSFER_PK;
        let vk_checksum = TransferZKPKeyChecksum::get();
	assert_eq!(vk.get_checksum(), vk_checksum);
```

File: src/test/frame.rs (hunk 9 above)
Comment (ghzlatarev) [reply src/test/frame.rs]: Right, was wondering what this was doing. Will put a ``` not_implemented!```
